export interface PtCard {
    CardID:number,
    CardTitle:string,
    CardValue:number,
    CardType:number,
    CardSubType:number,
    CardBadge:string,
    CardSeries:string,
    Year:number,
    Peak:string,
    Team:string,
    Franchise:string,
    FirstName:string,
    LastName:string,
    NickName:string,
    UniformNumber:number,
    DayOB:number,
    MonthOB:number,
    YearOB:number,
    Bats:number,
    Throws:number,
    Position:number,
    PitcherRole:number,
    Contact:number,
    Gap:number,
    Power:number,
    Eye:number,
    AvoidKs:number,
    BABIP:number,
    ContactvL:number,
    GapvL:number,
    PowervL:number,
    EyevL:number,
    AvoidKvL:number,
    BABIPvL:number,
    ContactvR:number,
    GapvR:number,
    PowervR:number,
    EyevR:number,
    AvoidKvR:number,
    BABIPvR:number,
    GBHitterType:number,
    FBHitterType:number,
    BattedBallType:number,
    Speed:number,
    StealRate:number,
    Stealing:number,
    Baserunning:number,
    Sacbunt:number,
    Buntforhit:number,
    Stuff:number,
    Movement:number,
    Control:number,
    pHR:number,
    pBABIP:number,
    StuffvL:number,
    MovementvL:number,
    ControlvL:number,
    pHRvL:number,
    pBABIPvL:number,
    StuffvR:number,
    MovementvR:number,
    ControlvR:number,
    pHRvR:number,
    pBABIPvR:number,
    Fastball:number,
    Slider:number,
    Curveball:number,
    Changeup:number,
    Cutter:number,
    Sinker:number,
    Splitter:number,
    Forkball:number,
    Screwball:number,
    Circlechange:number,
    Knucklecurve:number,
    Knuckleball:number,
    Stamina:number,
    Hold:number,
    GB:number,
    Velocity:number,
    ArmSlot:number,
    Height:number,
    InfieldRange:number,
    InfieldError:number,
    InfieldArm:number,
    DP:number,
    CatcherAbil:number,
    CatcherFrame:number,
    CatcherArm:number,
    OFRange:number,
    OFError:number,
    OFArm:number,
    PosRatingP:number,
    PosRatingC:number,
    PosRating1B:number,
    PosRating2B:number,
    PosRating3B:number,
    PosRatingSS:number,
    PosRatingLF:number,
    PosRatingCF:number,
    PosRatingRF:number,
    LearnC:number,
    Learn1B:number,
    Learn2B:number,
    Learn3B:number,
    LearnSS:number,
    LearnLF:number,
    LearnCF:number,
    LearnRF:number,
    era:number,
    MissionValue:number,
    limit:number,
    owned:number,
    brefid:string,
    date:number,
    LiveUpdateID:number,
    PtCardID:number,
    PtPredicts?:PtPredicts,
    ResultingTier:number,
    ResultingCardValue:number,
    tier:number,
}

export interface LiveUpdate {
    LiveUpdateID: number,
    StartDate: Date,
    EndDate?: Date,
    CycleYear: number,
}

export interface PtPredicts {
    [key: string]: number
}

export const liveUpdates = [
    {
        LiveUpdateID: 1,
        StartDate: new Date(2025, 2, 14),
        EndDate: new Date(2025, 4, 5),
        CycleYear: 2026,
    },
    {
        LiveUpdateID: 2,
        StartDate: new Date(2025, 4, 5),
        EndDate: new Date(2025, 5, 2),
        CycleYear: 2026,
    },
    {
        LiveUpdateID: 3,
        StartDate: new Date(2025, 5, 2),
        EndDate: new Date(2025, 6, 7),
        CycleYear: 2026,
    },
    {
        LiveUpdateID: 4,
        StartDate: new Date(2025, 6, 7),
        EndDate: new Date(2025, 7, 11),
        CycleYear: 2026,
    },
    {
        LiveUpdateID: 5,
        StartDate: new Date(2025, 7, 11),
        EndDate: new Date(2025, 8, 8),
        CycleYear: 2026,
    },
    {
        LiveUpdateID: 6,
        StartDate: new Date(2025, 8, 8),
        EndDate: new Date(2025, 9, 6),
        CycleYear: 2026,
    },
    {
        LiveUpdateID: 7,
        StartDate: new Date(2025, 9, 6),
        EndDate: new Date(2026, 2, 13),
        CycleYear: 2026,
    },
    {
        LiveUpdateID: 8,
        StartDate: new Date(2026, 2, 13),
        CycleYear: 2027,
    }
] as LiveUpdate[]