import {Option} from 'react-multi-select-component'

export enum Position {
    'P' = 1,
    'C' = 2,
    '1B' = 3,
    '2B' = 4,
    '3B' = 5,
    'SS' = 6,
    'LF' = 7,
    'CF' = 8,
    'RF' = 9,
    'DH' = 10,
}

export enum Tier {
    'Iron',
    'Bronze',
    'Silver',
    'Gold',
    'Diamond',
    'Perfect'
}

export enum Team {
    'Philadelphia Phillies',
    'Atlanta Braves',
    'Los Angeles Dodgers',
    'New York Yankees',
    'Cleveland Indians',
    'Seattle Mariners',
}

export enum Division {
    'NL East',
    'NL Central',
    'NL West',
    'AL East',
    'AL Central',
    'AL West',
}

export enum League {
    'National League',
    'American League',
}

export enum PredictSearchType {
    "Tier",
    "Team",
    "Division",
    "League",
    "Rookies",
    "LastYearsAllstars",
    "LastYearsAwardWinners",
}

export interface AppData {
    ptPredictPlayers: PtPredictPlayer[],
    setPtPredictPlayers: React.Dispatch<React.SetStateAction<PtPredictPlayer[]>>, 
    selectedTier: Option[],
    setSelectedTier: React.Dispatch<React.SetStateAction<Option[]>>,
    selectedTeam: Option[],
    setSelectedTeam: React.Dispatch<React.SetStateAction<Option[]>>,
    selectedDivision: Option[],
    setSelectedDivision: React.Dispatch<React.SetStateAction<Option[]>>,
    selectedLeague: Option[],
    setSelectedLeague: React.Dispatch<React.SetStateAction<Option[]>>,
}

export interface LiveUpdate {
    LiveUpdateID: number,
    EffectiveDate: string,
}

export interface GetPtCardPredictsRequest {
    TierFilter: number[],
    TeamFilter: number[],
    DivisionFilter: number[],
    LeagueFilter: number[],
    OnlyRookiesFilter: boolean,
    OnlyLastYearsAllstars: boolean,
    OnlyLastYearsAwardWinners: boolean,
    UserID: string,
    PageNumber: number,
    PageSize: number,
}

export interface PtPredict {
    PtPredictID?: number,
    PtCardID: number,
    CardID: number,
    LiveUpdateID: number,
    CardTitle: string,
    CardValue: number,
    Position: Position,
    PredictedTier?: number,
    UserID?: string,
}

export interface PostPtCardPredictRequest {
    PtCardPredictID?: number,
    CardID: number,
    PtCardID: number,
    PredictedTier: Tier,
}

export interface PostPtCardPredictResponse {
    PtCardPredictID: number,
    PtCardID: number,
    CardID: number,
}

export interface PtPredictPlayer {
    CardID: number,
    UserPredicts: PtPredict[],
}

export interface PtCard {
    CardID:number,
    CardTitle:string,
    CardValue:number,
    CardType:number,
    CardSubType:number,
    CardBadge:string,
    CardSeries:string,
    Year:number,
    Peak:string,
    Team:string,
    Franchise:string,
    FirstName:string,
    LastName:string,
    NickName:string,
    UniformNumber:number,
    DayOB:number,
    MonthOB:number,
    YearOB:number,
    Bats:number,
    Throws:number,
    Position:number,
    PitcherRole:number,
    Contact:number,
    Gap:number,
    Power:number,
    Eye:number,
    AvoidKs:number,
    BABIP:number,
    ContactvL:number,
    GapvL:number,
    PowervL:number,
    EyevL:number,
    AvoidKvL:number,
    BABIPvL:number,
    ContactvR:number,
    GapvR:number,
    PowervR:number,
    EyevR:number,
    AvoidKvR:number,
    BABIPvR:number,
    GBHitterType:number,
    FBHitterType:number,
    BattedBallType:number,
    Speed:number,
    StealRate:number,
    Stealing:number,
    Baserunning:number,
    Sacbunt:number,
    Buntforhit:number,
    Stuff:number,
    Movement:number,
    Control:number,
    pHR:number,
    pBABIP:number,
    StuffvL:number,
    MovementvL:number,
    ControlvL:number,
    pHRvL:number,
    pBABIPvL:number,
    StuffvR:number,
    MovementvR:number,
    ControlvR:number,
    pHRvR:number,
    pBABIPvR:number,
    Fastball:number,
    Slider:number,
    Curveball:number,
    Changeup:number,
    Cutter:number,
    Sinker:number,
    Splitter:number,
    Forkball:number,
    Screwball:number,
    Circlechange:number,
    Knucklecurve:number,
    Knuckleball:number,
    Stamina:number,
    Hold:number,
    GB:number,
    Velocity:number,
    ArmSlot:number,
    Height:number,
    InfieldRange:number,
    InfieldError:number,
    InfieldArm:number,
    DP:number,
    CatcherAbil:number,
    CatcherFrame:number,
    CatcherArm:number,
    OFRange:number,
    OFError:number,
    OFArm:number,
    PosRatingP:number,
    PosRatingC:number,
    PosRating1B:number,
    PosRating2B:number,
    PosRating3B:number,
    PosRatingSS:number,
    PosRatingLF:number,
    PosRatingCF:number,
    PosRatingRF:number,
    LearnC:number,
    Learn1B:number,
    Learn2B:number,
    Learn3B:number,
    LearnSS:number,
    LearnLF:number,
    LearnCF:number,
    LearnRF:number,
    era:number,
    MissionValue:number,
    limit:number,
    owned:number,
    brefid:string,
    date:number,
    LiveUpdateID:number,
    PtCardID:number,
}