import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { getAuthenticatedAppForUser } from '../lib/firebase/serverApp'
import { SignIn } from './SignIn';
import { headers } from 'next/headers';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const host = (await headers()).get('host');
  const isLocalhost = host?.startsWith('localhost') || host?.startsWith('127.0.0.1');

  const { currentUser } = await getAuthenticatedAppForUser(isLocalhost);

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="bg-gray-500 border">
          <SignIn initialUser={currentUser?.toJSON()} />
            {children}
        </div>
      </body>
    </html>
  );
}
